spring:
  application:
    name: socialnetwork

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /documentation.html

openapi:
  info:
    title: Social Network API
    description: Sistema desenvolvido para cumprir os requisitos do TP2 do Projeto de Bloco.
